# Site settings
title: Vinay Herur  
email: vinayherur@live.com
description: What's up world!
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social settings
500px_url:
facebook_url: https://www.facebook.com/vinayherur1
github_url: https://github.com/vinayherur
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/vinayherur/
linkedin_url: https://www.linkedin.com/in/vinay-herur/
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
